"""update avatar

Revision ID: dc8117dbe8e6
Revises: 0063f892644b
Create Date: 2025-09-15 18:15:04.093511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'dc8117dbe8e6'
down_revision: Union[str, Sequence[str], None] = '0063f892644b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_column('user', 'header_img')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('header_img', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
